### ISSUE TITLE
It's been long time no upgrade.

### ISSUE THREAD

**Issue by 9468305** [seadowg/deckard-kotlin#7]
Hi Mr Stott,

Your repo is very smart and pretty for demonstrate `mockito` with `kotlin`. But it's been long time no upgrade.  
Since `Robolectric` has already released 4.2 version.  Google is porting `android.test` to `AndroidX` library, which has a new `AndroidJUnitRunner`.  
For example: `constants = BuildConfig::class` has been removed from the latest `Robolectric`.
Do you have plan to update this repo?

**Comment by seadowg** [comment]
Hey @9468305 👋

I'm happy to try and keep it up to date if people are using it. It looks like this repo is still linked from robolectric/deckard (which I believe the Robolectric team is keeping up to date).

Always helpful to get PRs as well to give me a hand!
